version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todo_db
      - JWT_SECRET=your_super_secret_jwt_key
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx ts-node src/index.ts"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
